plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/EmptyMethod:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Rails/ActionOrder:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Metrics/ClassLength:
  Enabled: False
